SELECT UGB.TITLE, UGR.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, date_format(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_REPLY AS UGR
LEFT JOIN USED_GOODS_BOARD AS UGB ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE UGB.CREATED_DATE LIKE "2022-10%"
ORDER BY UGR.CREATED_DATE, UGB.TITLE;